# Generated by Django 6.0.3 on 2026-06-12 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('date_created', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('date_created', models.DateField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense_tracker_api.category')),
            ],
        ),
    ]
